# Generated by Django 4.1.3 on 2022-12-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_alter_category_name_alter_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
    ]
